---
title: "Tweets"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rmarkdown)
library(twitteR)
library(ROAuth)
library(httr)
library(plyr)
library(qdap)
library(stringr)
library(tm)
library(wordcloud)   
library("RColorBrewer")

#set twitter
api_key <- "bbmeTHKmB0yOp2tNxdi3N4yBe" # your api_key
api_secret <- "FZziVSsIqfwoWXyZg2lTror9rozOZCJYOCHlWsV8qYmInfRcdG" # your api_secret
access_token <- "500829754-O6wIL5kiyuhThm54Wy2qUTYJxGFX9yjI9ZALJKIH" # your access_token
access_token_secret <- "FwT0B8oVmuwwJz6aLUBM7ybJ1Vyvdnyk9UEreDFwsowPt" # your access_token_secret
setup_twitter_oauth(api_key, api_secret, access_token, access_token_secret)


urlPat<-function(x) gsub("(ftp|http)(s?)://.*\\b", "", x)
emlPat<-function(x) gsub("\\b[A-Z a-z 0-9._ - ]*(.*?)[.]{1,3} \\b", "", x)
tt<-function(x) gsub("RT |via", "", x)
tun<-function(x) gsub("[@][a - zA - Z0 - 9_]{1,15}", "", x)
ellipsis <- function(x) gsub("\u2026", "", x )

clean_corpus <- function(corpus){
#  corpus <- tm_map(corpus, tun)
  corpus <- tm_map(corpus, urlPat) 
  corpus <- tm_map(corpus, emlPat)
  corpus <- tm_map(corpus, ellipsis)
#  corpus <- tm_map(corpus, tt)
  corpus <- tm_map(corpus, function(x) iconv(x, to='UTF-8-MAC', sub='byte'))
  corpus <- tm_map(corpus, removePunctuation)
  coprus <- tm_map(corpus, stripWhitespace) #Strips White Space 
  corpus <- tm_map(corpus, tolower) #Changes case to lower case 
  corpus <- tm_map(corpus, removeWords, c(stopwords("en"), "rt", "http", "https", ". . .","..."))
  corpus <- tm_map(corpus, removeNumbers)
  corpus <- tm_map(corpus, PlainTextDocument)
  corpus <- Corpus(VectorSource(corpus))
  return(corpus)
}
```

This R Markdown document is made interactive using Shiny. Using this, you can search Twitter for a certain number tweets including any @Username, and generate a small wordcloud of the resulting dataset. More work and features are planned.

```{r eruptions, echo=FALSE}
fluidPage(
  fluidRow(
    column(4, wellPanel(
      selectInput("n_count", label = "Number of tweets", choices = c(25, 50, 100, 200, 500), selected = 100),
      textInput("search_phrase", label = "@Username:", value = "@WashingtonPost"),
      br(),
      actionButton("goButton", "Refresh")
    )),
    column(8,
      plotOutput("summary", width = 650, height = 650))
    )
    )

  output$summary <- renderPlot({

    input$goButton

tweets_dpm <- userTimeline(isolate(input$search_phrase), n = isolate(input$n_count), maxID=NULL, sinceID=NULL, includeRts=TRUE)
tweets_df <- twListToDF(tweets_dpm) #Convert to Data Frame
text <- Corpus(VectorSource(tweets_df$text), readerControl = list(language = "eng"))
cleanText <- clean_corpus(text)
tdm <- TermDocumentMatrix(cleanText) 
m1 <- as.matrix(tdm) 
v1<- sort(rowSums(m1),decreasing=TRUE) 
d1<- data.frame(word = names(v1),freq=v1) 

wordcloud(d1$word,d1$freq, min.freq = 2,max.words=200, random.order=FALSE, rot.per=0.35, colors=brewer.pal(9, "Greys"), scale=c(5,.5))
}, width=650, height=650)
```
